coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "test/**/*"
  - "coverage/**/*"
  - "dist/**/*"
  - "*.js"
  - "demo.js"
  - "cli.ts"